services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=to-tasty'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=tasty'
    ports:
      - '3307:3306'
