spring:
  application:
    name: to-tasty
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3307/to-tasty
    username: root
    password: verysecret
    driver-class-name: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      lifecycle-management: start_only

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace